dist: bionic
addons:
  chrome: stable
services:
  - xvfb
language: node_js
cache:
    directories:
        - node_modules
node_js:
  - "10"
before_install:
  - npm install -g npm
  - npm install -g karma-cli
script:
  - make check
notifications:
  email: false
sudo: false
env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - secure: G9oDQUXytNHni0wasGDXO3lQE/xuP9gd6VZ20kuh5FzVlqfY5L7JfYWki435nZ1z2yPD1QVAZi+1BCmCwnkTLVO9gB7cmDJDt1VzeHdCSOqCXGDAbOcq67/OO4FUa77sCQSDnqOOGVbiUPldaDl8G6uylk72Ll8b0pPwUWdRCM8=
  - secure: dniSzTSxXzaSGYjW3+LiNesx/BtTWo6RHuMKm19MwNo/YJYJJ/1YSEH/9vCmlVzc00CqvJ5Khwu9XPzcDV4gkuNQFN1+QcgGI2heVUqac/jqlGF39VEH8Xc+H40MsRLkwgSIkadIPWj4wBbbzqyC9M+J/KjUPOhBXGtp+FARu0I=
